namespace Hesternal.MathTool;


internal static class MathToolSettings
{
    public const string AutoGenComment = "// !!! GENERATED BY MathTool !!!";

    public const string MathModuleName = "HesternalEngine.Math";
    public const string Namespace      = "Hesternal";
    public const string MathNamespace  = Namespace + "::Math";

    public const int SbInitialCapacity = 3000;

    public static readonly string[] VectorFields = { "X", "Y", "Z", "W" };
    public static readonly string[] VectorFieldsLower = { "x", "y", "z", "w" };

    public static readonly string[] MatrixFields = { "C0", "C1", "C2", "C3" };
    public static readonly string[] MatrixFieldsLower = { "c0", "c1", "c2", "c3" };

    public static readonly string[] HandWrittenMathInternalPartitions =
    {
        "Functions",
        "Projection",
        "Rect",
        "Transform",
        "Quaternion",
        "QuaternionFunctions",
    };
}
